const path = require('path');
const fs = require('fs');
const { rootCertificates } = require('tls');
const { Pool } = require('pg');

// Na Vercel, as credenciais vêm das variáveis de ambiente do projeto.
if (!process.env.VERCEL) {
    require('dotenv').config({
        path: [path.join(__dirname, '.env'), path.join(__dirname, '../.env')],
        quiet: true
    });
}

let pool;
let inicializacao;

function obterPool() {
    if (pool) {
        return pool;
    }

    if (!process.env.DATABASE_URL) {
        const erro = new Error('Configure DATABASE_URL com a conexão PostgreSQL do Supabase.');
        erro.code = 'DATABASE_URL_AUSENTE';
        throw erro;
    }

    const endereco = new URL(process.env.DATABASE_URL);
    const bancoLocal = ['localhost', '127.0.0.1', '[::1]'].includes(endereco.hostname);
    const bancoSupabase = endereco.hostname.endsWith('.supabase.co') ||
        endereco.hostname.endsWith('.pooler.supabase.com');
    let certificado = process.env.DATABASE_SSL_CA?.replace(/\\n/g, '\n');

    // O Supabase usa uma CA própria, que não faz parte das raízes padrão do Node.
    if (!certificado && bancoSupabase) {
        certificado = [
            ...rootCertificates,
            fs.readFileSync(path.join(__dirname, 'certs', 'supabase-ca.crt'), 'utf8')
        ];
    }

    // Evita que parâmetros da URL sobrescrevam o certificado configurado.
    if (certificado) {
        for (const parametro of ['ssl', 'sslmode', 'sslrootcert', 'sslcert', 'sslkey']) {
            endereco.searchParams.delete(parametro);
        }
    }

    pool = new Pool({
        connectionString: endereco.toString(),
        ssl: bancoLocal ? false : {
            rejectUnauthorized: true,
            ...(certificado ? { ca: certificado } : {})
        },
        max: 1,
        connectionTimeoutMillis: 10000,
        idleTimeoutMillis: 5000,
        allowExitOnIdle: true
    });

    pool.on('error', (erro) => {
        console.error('Erro em uma conexão ociosa com o PostgreSQL:', erro.code || 'DATABASE_ERROR');
    });

    return pool;
}

async function inicializar() {
    if (!inicializacao) {
        inicializacao = obterPool().query(`
            CREATE TABLE IF NOT EXISTS public.produtos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                preco DOUBLE PRECISION NOT NULL,
                quantidade INTEGER NOT NULL
            )
        `).catch((erro) => {
            // Permite uma nova tentativa após uma falha temporária de conexão.
            inicializacao = null;
            throw erro;
        });
    }

    return inicializacao;
}

async function query(sql, parametros = []) {
    await inicializar();
    return obterPool().query(sql, parametros);
}

async function encerrar() {
    if (pool) {
        await pool.end();
        pool = undefined;
        inicializacao = undefined;
    }
}

module.exports = { query, inicializar, encerrar };
